#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Keeping this pretty light so it doesn't slow down our
# development workflow and we have the CI environment to
# do the time intensive tasks for us.
yarn workspace @apartmentsnapshot/snapshot-ui prettier:fix
git status #to list changes before added
git add -A
