#!/usr/bin/env sh

set -e

echo 'Building Docs 🚀'

node ./scripts/typedocs/index.js build src/services/index.ts --repo https://github.com/Apartment-Snapshot/snapshot-ui/tree/main/app
node ./scripts/typedocs/index.js build src/theme/index.ts --repo https://github.com/Apartment-Snapshot/snapshot-ui/tree/main/app

