#!/usr/bin/env sh

set -e

echo 'Building Docs 🚀'

# TypeDoc is used to generate a full documentation site in markdown
# for our non-component code.
yarn typedoc --out docs ./src/theme/index.ts ./src/services/index.ts

# We then move the API documentation for each package next to its
# associated code so we can import it into Storybook.
mv docs/modules/services.md src/services
mv docs/modules/theme.md src/theme

# Clean up the docs folder since we no longer need it
yarn rimraf docs

echo 'Donzo 💪'
